#!/bin/sh

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "##################################################### MEDICMINE INTEGRATE ################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

# ## ontologies
# ./gradlew integrate -Psource=go --stacktrace
# ./gradlew integrate -Psource=so --stacktrace
# ./gradlew integrate -Psource=plant-ontology --stacktrace
# ./gradlew integrate -Psource=plant-trait-ontology --stacktrace

# ## InterPro
# ./gradlew integrate -Psource=interpro --stacktrace
# ./gradlew integrate -Psource=interpro-go --stacktrace

# ## gene families
# ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K
# ./gradlew integrate --stacktrace -Psource=legume.genefam.fam1.M65K.trees_ML_rooted

# ## medtr
# ./gradlew integrate --stacktrace -Psource=medtr-about

# ## medtr.A17_HM341.gnm4
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.2GZ9
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.cds
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.mrna
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.protein
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.gene_models_main
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.legfed_v1_0.M65K.gfa
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.G3ZY.legfed_v1_0.M65K.pathway
# ./gradlew integrate --stacktrace -Psource=A17_HM341.gnm4.ann2.expr.RLZY

## medtr.R108_HM340.gnm1
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.XT6J
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.cds
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.mrna
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.protein
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.gene_models_main
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.legfed_v1_0.M65K.gfa
./gradlew integrate --stacktrace -Psource=R108_HM340.gnm1.ann1.85YW.legfed_v1_0.M65K.pathway

## medtr.jemalong_A17.gnm5
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.MVZ2
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.cds
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.mrna
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.protein
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.gene_models_main
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.gfa
./gradlew integrate --stacktrace -Psource=jemalong_A17.gnm5.ann1_6.L2RX.legfed_v1_0.M65K.pathway


## medsa
./gradlew integrate --stacktrace -Psource=medsa-about

## medsa.XinJiangDaYe.gnm1
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.12MR
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.cds
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.protein
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.transcript
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.gene_models_main
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.legfed_v1_0.M65K.gfa
./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.legfed_v1_0.M65K.pathway

## BROKEN FOR UNKNOWN REASONS
# ./gradlew integrate --stacktrace -Psource=XinJiangDaYe.gnm1.ann1.RKB9.iprscan

