#!/bin/sh

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "##################################################### MEDICMINE INTEGRATE ################################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies
./gradlew integrate -Psource=go --stacktrace
./gradlew integrate -Psource=so --stacktrace
./gradlew integrate -Psource=plant-ontology --stacktrace
./gradlew integrate -Psource=plant-trait-ontology --stacktrace

## InterPro
./gradlew integrate -Psource=interpro --stacktrace
./gradlew integrate -Psource=interpro-go --stacktrace

## LIS gene families
./gradlew integrate -Psource=lis.fam1-genefamily --stacktrace

## about 
./gradlew integrate -Psource=medtr-about --stacktrace
./gradlew integrate -Psource=medsa-about --stacktrace

## chromosome-fasta
./gradlew integrate -Psource=medtr.A17_HM341.gnm4-chromosome-fasta --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1-chromosome-fasta --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5-chromosome-fasta --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1-chromosome-fasta --stacktrace

## cds-fasta
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-cds-fasta --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-cds-fasta --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5.ann1_6-cds-fasta --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1.ann1-cds-fasta --stacktrace

## protein-fasta
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-protein-fasta --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-protein-fasta --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5.ann1_6-protein-fasta --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1.ann1-protein-fasta --stacktrace

## gff
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-gff --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-gff --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5.ann1_6-gff --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1.ann1-gff --stacktrace

## gfa
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-gfa --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-gfa --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5.ann1_6-gfa --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1.ann1-gfa --stacktrace

## pathway
./gradlew integrate -Psource=medtr.A17_HM341.gnm4.ann2-pathway --stacktrace
./gradlew integrate -Psource=medtr.R108_HM340.gnm1.ann1-pathway --stacktrace
./gradlew integrate -Psource=medtr.jemalong_A17.gnm5.ann1_6-pathway --stacktrace
./gradlew integrate -Psource=medsa.XinJiangDaYe.gnm1.ann1-pathway --stacktrace
